config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kuarters/', include('kuarters.urls')),

]

kuarters/urls.py
from unicodedata import name
from django.urls import path
from .views import (
    HomeView,
    TerimakasihView,
    ContactFormView,
    PermohonanCreateView,
    PermohonanListView,
    PermohonanDetailView,
    PermohonanUpdateView,
    PermohonanDeleteView,
)


app_name = "kuarters"
# domain.com/kuarters/pemohon_detail/1
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("terima_kasih/", TerimakasihView.as_view(), name="terima_kasih"),
    path("contact/", ContactFormView.as_view(), name="contact"),
    path(
        "create_permohonan/", PermohonanCreateView.as_view(), name="create_permohonan"
    ),
    path("senarai_pemohon", PermohonanListView.as_view(), name="senarai_pemohon"),
    path(
        "pemohon_detail/<int:pk>", PermohonanDetailView.as_view(), name="pemohon_detail"
    ),
    path(
        "update_pemohon/<int:pk>", PermohonanUpdateView.as_view(), name="update_pemohon"
    ),
    path(
        "delete_pemohon/<int:pk>", PermohonanDeleteView.as_view(), name="delete_pemohon"
    ),
]

kuarters/models.py
from django.db import models

# Create your models here.

STATUS_PILIHAN = [
    ("b", "bujang"),
    ("k", "berkahwin"),
]

TINGGAL_BERSAMA = (
    ("y", "ya"),
    ("t", "tidak"),
)


class Pemohon(models.Model):
    nama = models.CharField(max_length=200)
    no_kp = models.CharField(max_length=200)
    jawatan = models.CharField(max_length=200)
    tarikh_lahir = models.CharField(max_length=200)
    gred = models.CharField(max_length=10)
    # tarikh_mula_bekerja = models.DateField()
    elaun = models.CharField(max_length=50)
    no_tel_bimbit = models.CharField(max_length=40)
    status = models.CharField(max_length=1, choices=STATUS_PILIHAN)
    tinggal_bersama = models.CharField(max_length=1, choices=TINGGAL_BERSAMA)
    nama_pasangan = models.CharField(max_length=60)
    pekerjaan_pasangan = models.CharField(max_length=200)
    gaji = models.CharField(max_length=20)
    alamat_tempat_kerja = models.CharField(max_length=200)
    bil_anak = models.CharField(max_length=5)
    alamat_rumah = models.CharField(max_length=200)
    masih_menyewa = models.CharField(max_length=60)
    sewa_sebulan = models.CharField(max_length=10)
    detail = models.TextField(max_length=200)

    def __str__(self):
        return f"{self.nama} {self.no_kp} {self.status}"

kuarters/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

kuarters/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    FormView,
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse, reverse_lazy
from kuarters.forms import ContactForm

from kuarters.models import Pemohon

# Create your views here.


class HomeView(TemplateView):
    template_name = "kuarters/home.html"


class TerimakasihView(TemplateView):
    template_name = "kuarters/terima_kasih.html"


class PermohonanCreateView(CreateView):
    model = Pemohon
    # cipta templates guna nama model_form.html
    fields = "__all__"
    success_url = reverse_lazy("kuarters:terima_kasih")


class PermohonanListView(ListView):
    # cipta template gunakan nama model_list.html
    model = Pemohon
    queryset = Pemohon.objects.order_by("nama")
    context_object_name = "pemohon_list"


class PermohonanDetailView(DetailView):
    # RETURN ONLY ONE MODEL ENTRY PK
    # template gunakan nama model_detail.html
    model = Pemohon
    # PK --> {{pemohon}}


class PermohonanUpdateView(UpdateView):
    # SHARE model_form.html --- PK
    model = Pemohon
    fields = "__all__"
    success_url = reverse_lazy("kuarters:senarai_pemohon")


class PermohonanDeleteView(DeleteView):
    # Form --> Confirm Delete button
    # default template name :
    # model_confirm_delete.html
    model = Pemohon

    success_url = reverse_lazy("kuarters:senarai_pemohon")


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "kuarters/contact.html"

    # URL dan bukan template.html
    success_url = reverse_lazy("kuarters:terima_kasih")

    # apa yang nak dibuat dengan form?

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

kuarters/templates/kuarters/contact.html
<h1>Maklum balas </h1>

<form method="POST" action="">
    {% csrf_token %}
    
    {{form.as_p}}
    
    <input type="submit" value="submit" name="" id="">

</form>  

kuarters/templates/kuarters/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kuaters</title>
</head>



<body>
    <h1>Permohonan memduduki Kuarters</h1>
<ul>
    <li>
        <a href="{% url "kuarters:terima_kasih" %}">Terima Kasih</a>
    </li>


    <li>
        <a href="{% url "kuarters:contact" %}">Hubungi kami</a>
    </li>


    <li>
        <a href="{% url "kuarters:create_permohonan" %}">Buat permohonan baru</a>
    </li>


    <li>
        <a href="{% url "kuarters:senarai_pemohon" %}">Senarai permohonan kuarters</a>
    </li>

</ul>
    
</body>
</html>

kuarters/templates/kuarters/pemohon_confirm_delete.html
<h1>Anda pasti untuk delete permohonan ni </h1>
<h2>{{pemohon}}</h2>


<form method="POST" action="">
{% csrf_token %}

<input type="submit" value="Confirm Delete" >

</form>

kuarters/templates/kuarters/pemohon_detail.html
<h1>Detail View Pemohonan</h1>

{{ pemohon }}

kuarters/templates/kuarters/pemohon_form.html
<h1>Borang Permohonan</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Submit">
</form>

kuarters/templates/kuarters/pemohon_list.html
<h1>Senarai Permohonan duduk kuaters</h1>

<ul>
    {% for pemohon in pemohon_list %}

<li>
  <a href="/kuarters/pemohon_detail/{{pemohon.id}}">{{ pemohon.nama }} {{pemohon.no_kp}} {{pemohon.jawatan}}</a>

</li>

  <ul>
<li>
    <a href="/kuarters/update_pemohon/{{pemohon.id}}">Update Permohonan untuk {{pemohon.nama}} </a>
</li>
  </ul>


  <ul>
    <li>
        <a href="/kuarters/delete_pemohon/{{pemohon.id}}">Delete Permohonan untuk {{pemohon.nama}} </a>
    </li>
      </ul>
        

    {% endfor %}
</ul>
   

kuarters/templates/kuarters/terima_kasih.html
<h1>Terima Kasih</h1>